### PR TITLE
Remove NaN

### PR DESCRIPTION
**Pull request by mscharley**
Parallel PR to #20 to facilitate working together.

### CODE REVIEW

**Comment by mariszo** [comment]
after `boot dev`, the app at http://localhost:3000  hangs.

**Comment by mscharley** [comment]
Yep, it does - as noted in the commit message. It's a work in progress but this PR will need to knock off both bugs:

* The NaN issue
* The fact that half the application handles errors well and half doesn't.

The second mostly comes down to poor use of cells. There's quite a few places where there's more cells than necessary because I didn't know about lenses originally and now it's come back to bite me because those circular references don't work well with error handling.

**Comment by mariszo** [comment]
It looks better, but if you pass 0 for max threads field the app hangs. 
The problem is an infinite [seq](https://github.com/mscharley/parallelism-calculator/blob/remove-NaN/src/index.cljs.hl#L74) `(range 1 max 0)` . When you don't validate values at the enter point of app
you have to consider a lot of cases which should never happen in the domain of the problem which the app is trying to resolve.

**Comment by mscharley** [comment]
Yeah, there's still a few issues. The URL in the address bar is still not being updated either which is another regression.

**Comment by mscharley** [comment]
Actually, the real issue with the infinite range is that the `input` tag is validating the values but we don't care about its opinion and pass out a `v/value` for 0 (or negative numbers) instead of a `v/error`. Good catch there.

**Comment by mscharley** [comment]
> you have to consider a lot of cases which should never happen in the domain of the problem which the app is trying to resolve.

As a direct reply to this, passing the errors out actually makes more sense. What value do you pass out for an invalid value otherwise? The last value that was valid? That doesn't really make sense either - you could have some weird values showing up all over the place just because someone put in some weird value somewhere upstream. 

If however you pass the errors downstream you allow downstream to do something that makes sense. I haven't implemented it here (yet), but the ideal situation in this application would be to not display a graph at all - if any of the input is bad then the graph should be replaced with a message indicating there's an issue with some of your input. Passing the current invalid value downstream also makes sense. For instance, in the case of the URL routes you might want to store whatever input is there, valid or otherwise, to persist the users input faithfully.

**Comment by mscharley** [comment]
This way of handling things is similar to eg. Scala's `Try` class: http://danielwestheide.com/blog/2012/12/26/the-neophytes-guide-to-scala-part-6-error-handling-with-try.html

I'm still very much trying to learn Closure so my implementation is pretty weak so far but feedback/improvements are more than welcome.

**Comment by mscharley** [comment]
@mariszo and so here we are. This should get the app back to square one without this nasty bug. You should be able to type freely into any of the boxes and at worse it shouldn't break. There's a few places that are still perhaps aren't sensible - the URL won't preserve invalid input, the graph will attempt to generate something even if some of the inputs are invalid, etc. I'm happy to let this pass now though.

**Comment by mscharley** [comment]
This should also be able to close #21 now as well.

**Pull request merged**
